version: '3'
services:
  kdc:
    build: kdc
    privileged: true
  client:
    build: client
    privileged: true
    depends_on:
      - kdc
      - webserver
  webserver:
    build: webserver
    depends_on:
      - kdc
    ports:
      - "9292:9292"
